package com.idea.mulds.persistent.persistent2.entity;

import java.util.ArrayList;
import java.util.List;

public class TCustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public TCustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustomeridIsNull() {
            addCriterion("customerId is null");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNotNull() {
            addCriterion("customerId is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeridEqualTo(String value) {
            addCriterion("customerId =", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotEqualTo(String value) {
            addCriterion("customerId <>", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThan(String value) {
            addCriterion("customerId >", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThanOrEqualTo(String value) {
            addCriterion("customerId >=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThan(String value) {
            addCriterion("customerId <", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThanOrEqualTo(String value) {
            addCriterion("customerId <=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLike(String value) {
            addCriterion("customerId like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotLike(String value) {
            addCriterion("customerId not like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIn(List<String> values) {
            addCriterion("customerId in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotIn(List<String> values) {
            addCriterion("customerId not in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridBetween(String value1, String value2) {
            addCriterion("customerId between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotBetween(String value1, String value2) {
            addCriterion("customerId not between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyIsNull() {
            addCriterion("customerCompany is null");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyIsNotNull() {
            addCriterion("customerCompany is not null");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyEqualTo(String value) {
            addCriterion("customerCompany =", value, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyNotEqualTo(String value) {
            addCriterion("customerCompany <>", value, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyGreaterThan(String value) {
            addCriterion("customerCompany >", value, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyGreaterThanOrEqualTo(String value) {
            addCriterion("customerCompany >=", value, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyLessThan(String value) {
            addCriterion("customerCompany <", value, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyLessThanOrEqualTo(String value) {
            addCriterion("customerCompany <=", value, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyLike(String value) {
            addCriterion("customerCompany like", value, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyNotLike(String value) {
            addCriterion("customerCompany not like", value, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyIn(List<String> values) {
            addCriterion("customerCompany in", values, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyNotIn(List<String> values) {
            addCriterion("customerCompany not in", values, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyBetween(String value1, String value2) {
            addCriterion("customerCompany between", value1, value2, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomercompanyNotBetween(String value1, String value2) {
            addCriterion("customerCompany not between", value1, value2, "customercompany");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressIsNull() {
            addCriterion("customerAddress is null");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressIsNotNull() {
            addCriterion("customerAddress is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressEqualTo(String value) {
            addCriterion("customerAddress =", value, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressNotEqualTo(String value) {
            addCriterion("customerAddress <>", value, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressGreaterThan(String value) {
            addCriterion("customerAddress >", value, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressGreaterThanOrEqualTo(String value) {
            addCriterion("customerAddress >=", value, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressLessThan(String value) {
            addCriterion("customerAddress <", value, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressLessThanOrEqualTo(String value) {
            addCriterion("customerAddress <=", value, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressLike(String value) {
            addCriterion("customerAddress like", value, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressNotLike(String value) {
            addCriterion("customerAddress not like", value, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressIn(List<String> values) {
            addCriterion("customerAddress in", values, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressNotIn(List<String> values) {
            addCriterion("customerAddress not in", values, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressBetween(String value1, String value2) {
            addCriterion("customerAddress between", value1, value2, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomeraddressNotBetween(String value1, String value2) {
            addCriterion("customerAddress not between", value1, value2, "customeraddress");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeIsNull() {
            addCriterion("customerPostcode is null");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeIsNotNull() {
            addCriterion("customerPostcode is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeEqualTo(String value) {
            addCriterion("customerPostcode =", value, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeNotEqualTo(String value) {
            addCriterion("customerPostcode <>", value, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeGreaterThan(String value) {
            addCriterion("customerPostcode >", value, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("customerPostcode >=", value, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeLessThan(String value) {
            addCriterion("customerPostcode <", value, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeLessThanOrEqualTo(String value) {
            addCriterion("customerPostcode <=", value, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeLike(String value) {
            addCriterion("customerPostcode like", value, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeNotLike(String value) {
            addCriterion("customerPostcode not like", value, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeIn(List<String> values) {
            addCriterion("customerPostcode in", values, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeNotIn(List<String> values) {
            addCriterion("customerPostcode not in", values, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeBetween(String value1, String value2) {
            addCriterion("customerPostcode between", value1, value2, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomerpostcodeNotBetween(String value1, String value2) {
            addCriterion("customerPostcode not between", value1, value2, "customerpostcode");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNull() {
            addCriterion("customerName is null");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNotNull() {
            addCriterion("customerName is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernameEqualTo(String value) {
            addCriterion("customerName =", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotEqualTo(String value) {
            addCriterion("customerName <>", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThan(String value) {
            addCriterion("customerName >", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThanOrEqualTo(String value) {
            addCriterion("customerName >=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThan(String value) {
            addCriterion("customerName <", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThanOrEqualTo(String value) {
            addCriterion("customerName <=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLike(String value) {
            addCriterion("customerName like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotLike(String value) {
            addCriterion("customerName not like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameIn(List<String> values) {
            addCriterion("customerName in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotIn(List<String> values) {
            addCriterion("customerName not in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameBetween(String value1, String value2) {
            addCriterion("customerName between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotBetween(String value1, String value2) {
            addCriterion("customerName not between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneIsNull() {
            addCriterion("customerPhone is null");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneIsNotNull() {
            addCriterion("customerPhone is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneEqualTo(String value) {
            addCriterion("customerPhone =", value, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneNotEqualTo(String value) {
            addCriterion("customerPhone <>", value, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneGreaterThan(String value) {
            addCriterion("customerPhone >", value, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneGreaterThanOrEqualTo(String value) {
            addCriterion("customerPhone >=", value, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneLessThan(String value) {
            addCriterion("customerPhone <", value, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneLessThanOrEqualTo(String value) {
            addCriterion("customerPhone <=", value, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneLike(String value) {
            addCriterion("customerPhone like", value, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneNotLike(String value) {
            addCriterion("customerPhone not like", value, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneIn(List<String> values) {
            addCriterion("customerPhone in", values, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneNotIn(List<String> values) {
            addCriterion("customerPhone not in", values, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneBetween(String value1, String value2) {
            addCriterion("customerPhone between", value1, value2, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomerphoneNotBetween(String value1, String value2) {
            addCriterion("customerPhone not between", value1, value2, "customerphone");
            return (Criteria) this;
        }

        public Criteria andCustomeremailIsNull() {
            addCriterion("customerEmail is null");
            return (Criteria) this;
        }

        public Criteria andCustomeremailIsNotNull() {
            addCriterion("customerEmail is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeremailEqualTo(String value) {
            addCriterion("customerEmail =", value, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailNotEqualTo(String value) {
            addCriterion("customerEmail <>", value, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailGreaterThan(String value) {
            addCriterion("customerEmail >", value, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailGreaterThanOrEqualTo(String value) {
            addCriterion("customerEmail >=", value, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailLessThan(String value) {
            addCriterion("customerEmail <", value, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailLessThanOrEqualTo(String value) {
            addCriterion("customerEmail <=", value, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailLike(String value) {
            addCriterion("customerEmail like", value, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailNotLike(String value) {
            addCriterion("customerEmail not like", value, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailIn(List<String> values) {
            addCriterion("customerEmail in", values, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailNotIn(List<String> values) {
            addCriterion("customerEmail not in", values, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailBetween(String value1, String value2) {
            addCriterion("customerEmail between", value1, value2, "customeremail");
            return (Criteria) this;
        }

        public Criteria andCustomeremailNotBetween(String value1, String value2) {
            addCriterion("customerEmail not between", value1, value2, "customeremail");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}