package com.idea.mulds.persistent.persistent2.entity;

import java.io.Serializable;

public class TCustomer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerId
     *
     * @mbg.generated
     */
    private String customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerCompany
     *
     * @mbg.generated
     */
    private String customercompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerAddress
     *
     * @mbg.generated
     */
    private String customeraddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerPostcode
     *
     * @mbg.generated
     */
    private String customerpostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerName
     *
     * @mbg.generated
     */
    private String customername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerPhone
     *
     * @mbg.generated
     */
    private String customerphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.customerEmail
     *
     * @mbg.generated
     */
    private String customeremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerId
     *
     * @return the value of t_customer.customerId
     *
     * @mbg.generated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerId
     *
     * @param customerid the value for t_customer.customerId
     *
     * @mbg.generated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerCompany
     *
     * @return the value of t_customer.customerCompany
     *
     * @mbg.generated
     */
    public String getCustomercompany() {
        return customercompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerCompany
     *
     * @param customercompany the value for t_customer.customerCompany
     *
     * @mbg.generated
     */
    public void setCustomercompany(String customercompany) {
        this.customercompany = customercompany == null ? null : customercompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerAddress
     *
     * @return the value of t_customer.customerAddress
     *
     * @mbg.generated
     */
    public String getCustomeraddress() {
        return customeraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerAddress
     *
     * @param customeraddress the value for t_customer.customerAddress
     *
     * @mbg.generated
     */
    public void setCustomeraddress(String customeraddress) {
        this.customeraddress = customeraddress == null ? null : customeraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerPostcode
     *
     * @return the value of t_customer.customerPostcode
     *
     * @mbg.generated
     */
    public String getCustomerpostcode() {
        return customerpostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerPostcode
     *
     * @param customerpostcode the value for t_customer.customerPostcode
     *
     * @mbg.generated
     */
    public void setCustomerpostcode(String customerpostcode) {
        this.customerpostcode = customerpostcode == null ? null : customerpostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerName
     *
     * @return the value of t_customer.customerName
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerName
     *
     * @param customername the value for t_customer.customerName
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerPhone
     *
     * @return the value of t_customer.customerPhone
     *
     * @mbg.generated
     */
    public String getCustomerphone() {
        return customerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerPhone
     *
     * @param customerphone the value for t_customer.customerPhone
     *
     * @mbg.generated
     */
    public void setCustomerphone(String customerphone) {
        this.customerphone = customerphone == null ? null : customerphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.customerEmail
     *
     * @return the value of t_customer.customerEmail
     *
     * @mbg.generated
     */
    public String getCustomeremail() {
        return customeremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.customerEmail
     *
     * @param customeremail the value for t_customer.customerEmail
     *
     * @mbg.generated
     */
    public void setCustomeremail(String customeremail) {
        this.customeremail = customeremail == null ? null : customeremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerid=").append(customerid);
        sb.append(", customercompany=").append(customercompany);
        sb.append(", customeraddress=").append(customeraddress);
        sb.append(", customerpostcode=").append(customerpostcode);
        sb.append(", customername=").append(customername);
        sb.append(", customerphone=").append(customerphone);
        sb.append(", customeremail=").append(customeremail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}