package com.idea.mulds.persistent.persistent2.entity;

import java.io.Serializable;

public class TLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.logid
     *
     * @mbg.generated
     */
    private Integer logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.loguser
     *
     * @mbg.generated
     */
    private String loguser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.logtime
     *
     * @mbg.generated
     */
    private String logtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.logtype
     *
     * @mbg.generated
     */
    private String logtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.logid
     *
     * @return the value of t_log.logid
     *
     * @mbg.generated
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.logid
     *
     * @param logid the value for t_log.logid
     *
     * @mbg.generated
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.loguser
     *
     * @return the value of t_log.loguser
     *
     * @mbg.generated
     */
    public String getLoguser() {
        return loguser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.loguser
     *
     * @param loguser the value for t_log.loguser
     *
     * @mbg.generated
     */
    public void setLoguser(String loguser) {
        this.loguser = loguser == null ? null : loguser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.logtime
     *
     * @return the value of t_log.logtime
     *
     * @mbg.generated
     */
    public String getLogtime() {
        return logtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.logtime
     *
     * @param logtime the value for t_log.logtime
     *
     * @mbg.generated
     */
    public void setLogtime(String logtime) {
        this.logtime = logtime == null ? null : logtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.logtype
     *
     * @return the value of t_log.logtype
     *
     * @mbg.generated
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.logtype
     *
     * @param logtype the value for t_log.logtype
     *
     * @mbg.generated
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype == null ? null : logtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logid=").append(logid);
        sb.append(", loguser=").append(loguser);
        sb.append(", logtime=").append(logtime);
        sb.append(", logtype=").append(logtype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}